### ISSUE TITLE
Brick demo doesn't work quite right

### ISSUE THREAD

**Issue by GaryThomas** [Unity-Technologies/2d-techdemos#10]

**Comment by GaryThomas** [comment]
Using Unity 2018.3.6f1, the brick demo seems to start out OK, but I can't ever hit/clear anything but the lowest layer of blocks.   Adding some logging shows that the lowest colliders are still active even after the sprite has been nulled out.

**Comment by ChuanXin-Unity** [comment]
Sorry about that! There is an issue with Unity 2018.3.6f1 which will be fixed with Unity 2018.3.8f1.
