### ISSUE TITLE
Compilation error about GridInfo

### ISSUE THREAD

**Issue by vincismurf** [Unity-Technologies/2d-techdemos#14]
Destructible.cs(68,22): error CS0246: The type or namespace name 'GridInformation'

2019.2.0f1

BTW this:
"com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#master",

Does not work, 

I had to download and install into Assets manually

**Comment by ChuanXin-Unity** [comment]
I believe you will need to have `Git` installed and configured for the manifest file to work correctly.

I will see if there is a way where you can just download a branch of this repository as a project and have it work without you having to have `Git` installed.
