### ISSUE TITLE
Add Hexagonal Tilemap example

### ISSUE THREAD

**Issue by RyotaMurohoshi** [Unity-Technologies/2d-techdemos#18]
How about add Hexagonal Tilemap example assets and scene?

This project is so useful to describe Tilemap feature and Hexagonal Tilemap is one of the important feature for tilemap.

I think it is so good to add Hexagonal Tilemap example to 2d-techdemos.

**Comment by ChuanXin-Unity** [comment]
That sounds like a good idea! We will add examples for Hexagonal Tilemaps.

**Comment by RyotaMurohoshi** [comment]
Thank you!

I am glad if there are both example for flat top hexagonal tilemap and point top hexagonal tilemap!

I am looking forward to use hexagonal tilemap example in 2d-techdemos.

**Comment by RyotaMurohoshi** [comment]
Thank you for your developing for Hexagonal Tilemap!

So nice!
