### ISSUE TITLE
Use Git tag for 2d-extras dependency instead of branch.

### ISSUE THREAD

**Issue by RyotaMurohoshi** [Unity-Technologies/2d-techdemos#20]
2d-extras has git tag to add dependency for 2d-extras Unity Project.

see : https://github.com/Unity-Technologies/2d-extras/issues/152

This 2d-techdemos use `master` not git tag.

https://github.com/Unity-Technologies/2d-techdemos/blob/d5325f0206a6cd43d09cd60b7fea972502dae379/Packages/manifest.json#L6

So, auto diff will be appear when 2d-extras master is updated.

To avoid this auto diff, I proposed using git tag for 2d-extras dependency.

**Comment by RyotaMurohoshi** [comment]
When I create this PR https://github.com/Unity-Technologies/2d-techdemos/pull/19, auto diff is created.

So I want to avoid this auto diff.

**Comment by ChuanXin-Unity** [comment]
In the future, when the package is available on Unity Package Manager, we would change this to use the Unity package available instead of using git to pull the source from the repository. This would also be better for users who do not have or do not use git as well.

**Comment by RyotaMurohoshi** [comment]
I got it.

I close this issue.
