### ISSUE TITLE
Error after import

### ISSUE THREAD

**Issue by lihaoGitHub** [Unity-Technologies/2d-techdemos#26]
version: Unity 2020.3.18f1
url: https://github.com/Unity-Technologies/2d-extras.git
When I use Package Manager to import, one error is reported in the console.
Library/PackageCache/com.unity.2d.tilemap.extras@acb3c5a884/Editor/Tiles/RuleTile/RuleTileEditor.cs(327,26): error CS1061: 'ReorderableList' does not contain a definition for 'IsSelected' and no accessible extension method 'IsSelected' accepting a first argument of type 'ReorderableList' could be found (are you missing a using directive or an assembly reference?)

**Comment by ChuanXin-Unity** [comment]
Sorry about this! Could you use https://github.com/Unity-Technologies/2d-techdemos/tree/2020.3 instead as you are using the 2020.3 Unity Editor? Thanks!

**Comment by lihaoGitHub** [comment]
Thanks for your help.  it is work,  I use https://github.com/Unity-Technologies/2d-extras.git#2020.3
