### ISSUE TITLE
Normal Mapping does not work with Unity 2021.1.27f1

### ISSUE THREAD

**Issue by NathanDelorme** [Unity-Technologies/2d-techdemos#27]
I tried to import the files into my project, however the scene example's tilemap appears purple. In the "Normal Mapped Tile" shader, there is an annotation that says: "Material property is found in another cbuffer than "UnityPerMaterial"(_MainText_ST)".

**Comment by ChuanXin-Unity** [comment]
Hi, could you share what packages you have in your project? You can find that out by checking Windows/Package Manager and changing the Packages view to Packages: In Project on the top left.

**Comment by NathanDelorme** [comment]
![Packages](https://user-images.githubusercontent.com/29151966/149048161-4fd0fa8a-1bef-43f3-9d8b-1afd5e969208.png)

**Comment by NathanDelorme** [comment]
Here are the packages I have installed on my project.

**Comment by ChuanXin-Unity** [comment]
I assume you are using the 2D Renderer as your graphics pipeline as you have the Universal RP package installed?

Unfortunately, this scene (normal mapping) and shader is meant to work with the default renderer in the Unity Editor (without any renderer pipeline set).

If you would like to use normal mapping with the Tilemap with the 2D Renderer, you could follow the manual at https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@11.0/manual/SecondaryTextures.html instead!

**Comment by NathanDelorme** [comment]
Thank you very much, I found this solution literally 5 hours before your message. I close the issue.
