### ISSUE TITLE
Read.me

### ISSUE THREAD

**Issue by DavidMS** [Unity-Technologies/2d-techdemos#6]
Hi, this is not a proper issue, but I'd like to complete the Read.me file for other people that will come in the futura. The problem is that me myself don't have a clue about how to use the tools in the project. Would anyone mind to give me some help? Thanks in advance.

**Comment by ChuanXin-Unity** [comment]
The README file has been updated with some information about the repository and how to use it. Information about some of the scripts here can be found in 2d-extras instead as this repository contains the asset implementation of them.

Is there any other information you would like to have?

**Comment by DavidMS** [comment]
Thank you very much! I think is enought with this.
