### ISSUE TITLE
Missing Asset

### ISSUE THREAD

**Issue by pvaniawala** [Unity-Technologies/2d-techdemos#7]
Upon loading the project the following error is observed. 
Hexagonal rule tile asset may be missing from the project.

Removing Assets/Tilemap/Rule Tiles/Hexagonal Tile because the asset does not exist

**Comment by ChuanXin-Unity** [comment]
Fixed at c160314fb22f471ded5af2ad5c2fbcac39a52928. 

Thanks for notifying!
