### ISSUE TITLE
How do I use this in Unity?

### ISSUE THREAD

**Issue by donkobonko** [Unity-Technologies/2d-techdemos#9]
I'm trying use the assets, but I can't seem to use it in the Tile Palette. I'm following the instructions:
To view the examples in an existing Unity project, please copy the contents in the Assets folder to the Assets folder of your existing project.

I do that, but then it doesn't show anything in the Tile Palette. I try to right click and then check the "Select Tile Asset" but.. it doesn't work.

**Comment by ChuanXin-Unity** [comment]
Hi, sorry for the late reply. Could share the version of Unity you are using? Also, are you able to view all the assets when you download and use this as your Unity project directly?
